<script type="text/javascript" language="javascript" class="init">
	$(document).ready(function() {
		$('#usuarios').DataTable();
	} );
</script>
<?php 
//$mensaje = $this->session->get("mensaje");
$limpiar = $this->session->get("clear");
if($limpiar == 1){
	echo '<script type="text/javascript">
$( document ).ready(function() {
	document.getElementById("uNombre").value = "";
	document.getElementById("uApellido").value = "";
	document.getElementById("uCodigo").value = "";
	document.getElementById("uPass").value = "";
	document.getElementById("uPass2").value = "";
});
</script>'; 
	
}
echo $this->view->titulo;
echo $this->getContent();
echo $this->view->form;
echo $this->view->tabla;
?>