<link rel="stylesheet" href="css/dabblet.css">
<script type="text/javascript" src="js/form.js"></script>
<?php 
echo $this->view->titulo;
echo $this->getContent();
?>

<div id="dtrans" name="dtrans">
<table id="trans">
	<thead>
		<th>Cliente</th><th colspan="2">Factura</th><th colspan="2">Pago</th><th>Dev/Error</th>
	</thead>
	<thead>
		<th>cod - nombre</th><th>F</th><th>E</th><th>E</th><th>C</th><th></th>
	</thead>
	<tbody>
	<?php
		$body = ""; 
		$class = "white number";
		$dirClientes = CrDirecciones::find("di_ruta = ".$this->view->ruta);
		foreach ($dirClientes as $dc){
			$c = CrClientes::findFirst("cl_codigo = $dc->di_cliente");
			$body = $body."<tr><td>".$c->cl_codigo." - ".$c->cl_nombre."</td>".
			"<td>".$this->tag->textField(array("f$c->cl_codigo","id" => "f$c->cl_codigo", "class" => $class))."</td>".
			"<td>".$this->tag->textField(array("ea$c->cl_codigo","id" => "ea$c->cl_codigo", "class" => $class))."</td>".
			"<td>".$this->tag->textField(array("eb$c->cl_codigo","id" => "eb$c->cl_codigo", "class" => $class))."</td>".
			"<td>".$this->tag->textField(array("c$c->cl_codigo","id" => "c$c->cl_codigo", "class" => $class))."</td>".
			"<td>".$this->tag->textField(array("dev$c->cl_codigo","id" => "dev$c->cl_codigo", "class" => $class))."</td>".
			"</tr>";
			if($class == "white number"){
				$class = "grey number";
			}else{
				$class = "white number";
			}
		}
		echo $body;
	?>		
	</tbody>
</table>
</div>

<div id="rtable" name="rtable">
<h3>Gastos</h3>
<div id="dgastos" name="dgastos">
<table id="gastos">
	<thead>
		<th>Razon</th><th>Monto</th>
	</thead>
	<tbody>
		<td>Gasolina</td><td>30.00</td>
	</tbody>
</table>
</div>

<h3>Prestamos</h3>
<div id="dprestamos" name="dprestamos">
<table id="prestamos">	<thead>		<th>Razon</th><th>Monto</th>	</thead>	<tbody>		<td>Gasolina</td><td>30.00</td>	</tbody></table>
</div>
<h3>Otros</h3>
<div id="dotros" name="dotros"><table id="otros">	<thead>		<th>Razon</th><th>Monto</th>	</thead>	<tbody>		<td>Gasolina</td><td>30.00</td>	</tbody></table>
</div>
<h3>Detalle</h3>
<div id="detalle" >
</div>
</div>

<div id="totales" name="totales>
<table id="ttotal">
	<tbody>
		<tr>
			<td>Total Efectivo:</td><td><div id="tefectivo" name="tefectivo"></div></td>
			<td>Total Cheque:</td><td><div id="tcheque" name="tcheque"></div></td>
			<td>Total Global:</td><td><div id="tglobal" name="tglobal"></div></td>
	</tbody>
</table>
</div>